version: '3.8'

services:
  app:
    build: .
    container_name: shipping_data_app
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./config:/app/config
    depends_on:
      - db
    networks:
      - data_net
    ports:
      - "8000:8000"  # Reserved for FastAPI later

  db:
    image: postgres:15
    container_name: shipping_data_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"  # Local access for pgAdmin or DBeaver
    networks:
      - data_net

volumes:
  pgdata:

networks:
  data_net: