version: '3.8'

services:
  app:
    build: .
    container_name: analytics_api
    env_file: .env
    environment:
      DB_HOST: db       
      DB_PORT: 5432 
    working_dir: /app/analytics_api
    volumes:
      - ./analytics_api:/app/analytics_api
      - ./config:/app/config
    depends_on:
      - db
    networks:
      - data_net
    ports:
      - "8000:8000"  
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  db:
    image: postgres:15
    container_name: shipping_data_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"  # Local access for pgAdmin or DBeaver
    networks:
      - data_net
  telegram_scraper:
    build: .
    container_name: telegram_scraper
    working_dir: /app/src/services
    command: ["python", "telegram_scrapper.py"]
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
    env_file: .env
    networks:
      - data_net

volumes:
  pgdata:

networks:
  data_net:

