version: 2

models:
  - name: top_3_products_per_channel
    description: "An example aggregated table showing the top 3 most mentioned products in each Telegram channel"
    columns:
      - name: product_name
        description: "Name of the mentioned product"
        test:
          - not_null 
          - unique
      - name: channel_name
        description: "Telegram channel where the product was mentioned"
      - name: mention_count
        description: "Number of times the product was mentioned in that channel"
      - name: rank
        description: "Ranking of the product within the channel based on mentions"